"""research/claims-matrix.md from research/claims.toml and the published run: claim → experiment → hypothesis → facts.

    python3 tools/build_claims_matrix.py

Every value is read from enterprise_knowledge_rag_poc/runs/<PUBLISHED>/facts.json or docs/derived-facts.json (post-hoc,
`x.` keys), never typed. A claim fails the build when a fact key is unknown, or when its class contradicts the verdict of
its hypothesis (SUPPORTED needs SUPPORTED, NOT SUPPORTED needs NOT SUPPORTED, NEGATIVE CONTROL needs SUPPORTED: the
control was preregistered to fail, and did).
"""

from __future__ import annotations

import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
POC = ROOT / "enterprise_knowledge_rag_poc"
NEEDS = {"SUPPORTED": "SUPPORTED", "NOT SUPPORTED": "NOT SUPPORTED", "NEGATIVE CONTROL": "SUPPORTED"}


def main() -> None:
    run = (POC / "runs" / "PUBLISHED").read_text().strip()
    facts = json.loads((POC / "runs" / run / "facts.json").read_text())
    dp = ROOT / "docs" / "derived-facts.json"
    facts.update(json.loads(dp.read_text()) if dp.exists() else {})
    claims = tomllib.loads((ROOT / "research" / "claims.toml").read_text())["claims"]
    errors = []
    out = ["# S2 · claims matrix", "",
           f"Generated by `tools/build_claims_matrix.py` from `research/claims.toml` and run `{run}`. Every value is read from "
           "`facts.json` (or `docs/derived-facts.json` for post-hoc `x.` keys); none is typed. A class that contradicts its "
           "hypothesis's verdict fails the build.", "",
           "| claim | class | statement | experiments | hypothesis | where | facts (value · source) |", "|---|---|---|---|---|---|---|"]
    for c in claims:
        h = c.get("hypothesis")
        verdict = facts[h]["value"] if h and h in facts else None
        if h and verdict is None:
            errors.append(f"{c['id']}: hypothesis {h} has no verdict")
        need = NEEDS.get(c["class"])
        if need and verdict != need:
            errors.append(f"{c['id']}: class {c['class']} but {h} is {verdict}")
        cells = []
        for k in c["facts"]:
            if k not in facts:
                errors.append(f"{c['id']}: unknown fact {k}")
                continue
            v = facts[k]["value"]
            cells.append(f"`{k}` = {json.dumps(v, ensure_ascii=False)} · {facts[k]['source']}")
        hv = f"{h}: {verdict}" if h else "—"
        out.append(f"| {c['id']} | {c['class']} | {c['statement']} | {', '.join(c['experiments'])} | {hv} | {'; '.join(c['article'])} | {'<br>'.join(cells)} |")
    if errors:
        sys.exit("claims matrix:\n  " + "\n  ".join(errors))
    (ROOT / "research" / "claims-matrix.md").write_text("\n".join(out) + "\n")
    print(f"{len(claims)} claims -> research/claims-matrix.md")


if __name__ == "__main__":
    main()
