"""docs/source/report.src.md: the run report, generated from the published run's rows (never typed by hand).

    python3 tools/build_report_source.py

Per-case tables for every experiment, so a reader can audit any headline number down to the case and the unit. The
numbers in this file are computed here from runs/<PUBLISHED>/*.jsonl; tools/build_docs.py then renders it like the
editions (it may also use {{fact}} tokens).
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POC = ROOT / "enterprise_knowledge_rag_poc"
RUN = (POC / "runs" / "PUBLISHED").read_text().strip()
R = POC / "runs" / RUN


def rows(name):
    p = R / name
    return [json.loads(x) for x in p.read_text().splitlines() if x.strip()] if p.exists() else []


def tick(b):
    return "✓" if b else "✗"


def main():
    out = ["---", "title: Run report: every case, every experiment", f"subtitle: Every held-out case, every experiment, from run {RUN}. Generated from the recorded rows; nothing typed by hand.",
           "byline: S2 · Production AI Engineering", "kicker: Production AI Engineering · S2 · Run report", "filed: 2026-10-08", "run: Recorded run {{run.id}}",
           "tags: RAG, Evaluation, Enterprise Search", "---", "",
           "This report is generated by `tools/build_report_source.py` from `enterprise_knowledge_rag_poc/runs/{{run.id}}/`. "
           "Labels are in `groundtruth/labels.yaml`; definitions in the technical edition §4.1 and §7.", ""]
    A = rows("a.jsonl")
    out += ["## A · Retrieval: needed index units in the top 10 (no filter)", "",
            "| case | needed | vector | BM25 | hybrid | invalid in vector top 5 |", "|---|---|---|---|---|---|"]
    for cid in sorted({r["case_id"] for r in A}, key=lambda c: (c[2], len(c), c)):
        rs = {r["method"]: r for r in A if r["case_id"] == cid and r.get("prefilter") is False}
        if not rs.get("vector") or not rs["vector"]["needed"]:
            continue
        n = len(rs["vector"]["needed"])
        cell = lambda m: f"{sum(u in rs[m]['ranked'][:10] for u in rs[m]['needed'])}/{n}"
        out.append(f"| {cid} | {n} | {cell('vector')} | {cell('bm25')} | {cell('hybrid')} | {len(rs['vector']['invalid_top5'])} |")
    sr = [r for r in A if r["method"] == "structured-route" and r["records"]]
    out += ["", "**A2 · structured records.** For each needed record: returned by the structured route; exact fields found together in a top-20 prose unit.", "",
            "| case | record | route | vector | BM25 | hybrid |", "|---|---|---|---|---|---|"]
    for r in sr:
        for rec in r["records"]:
            out.append(f"| {r['case_id']} | `{rec}` | {tick(rec in r['route_returned'])} | {tick(rec in r['prose_has_fields']['vector'])} | "
                       f"{tick(rec in r['prose_has_fields']['bm25'])} | {tick(rec in r['prose_has_fields']['hybrid'])} |")
    B = rows("b.jsonl")
    out += ["", "## B · Admission over the same frozen candidates", "",
            "| case | pool invalid | naive: invalid in context | naive: unreadable | governed: invalid | governed: unreadable | needed kept naive | needed kept governed |",
            "|---|---|---|---|---|---|---|---|"]
    for cid in sorted({r["case_id"] for r in B}, key=lambda c: (c[2], len(c), c)):
        n = next(r for r in B if r["case_id"] == cid and r["arm"] == "naive")
        g = next(r for r in B if r["case_id"] == cid and r["arm"] == "governed")
        need = len(g["needed_in_pool"])
        out.append(f"| {cid} | {n['pool_audit']['invalid']} | {n['ctx_invalid']} | {n['ctx_unauthorized']} | {g['ctx_invalid']} | {g['ctx_unauthorized']} | "
                   f"{len(n['needed_in_context'])}/{need} | {len(g['needed_in_context'])}/{need} |")
    out += ["", "Invalid units the naive arm let in, by case:", ""]
    for cid in sorted({r["case_id"] for r in B}, key=lambda c: (c[2], len(c), c)):
        n = next(r for r in B if r["case_id"] == cid and r["arm"] == "naive")
        if n["ctx_invalid_units"]:
            out.append(f"- **{cid}**: " + ", ".join(f"`{u}`" for u in n["ctx_invalid_units"]))
    C = rows("c.jsonl")
    out += ["", "## C · Packing, same admitted pool: needed units fully present · qualifiers kept", "",
            "| case | " + " | ".join(f"{b} truncate | {b} assembler" for b in (300, 450, 600, 900)) + " |",
            "|---|" + "---|" * 8]
    for cid in sorted({r["case_id"] for r in C}, key=lambda c: (c[2], len(c), c)):
        cells = []
        for b in (300, 450, 600, 900):
            for m in ("truncate", "assembler"):
                r = next(x for x in C if x["case_id"] == cid and x["budget"] == b and x["method"] == m)
                q = r["qualifiers"]
                cells.append(f"{len(r['needed_covered'])}/{len(r['needed_in_pool'])}" + (f" · q {sum(q.values())}/{len(q)}" if q else ""))
        out.append(f"| {cid} | " + " | ".join(cells) + " |")
    D = rows("d.jsonl")
    seeds = sorted({r["seed"] for r in D})
    out += ["", f"## D · End to end, {len(seeds)} seed(s): correct runs (naive · governed raw · governed bound)", "",
            "| case | naive | governed raw | governed bound | naive leaks | naive forbidden action | governed binding changed |", "|---|---|---|---|---|---|---|"]
    for cid in sorted({r["case_id"] for r in D}, key=lambda c: (c[2], len(c), c)):
        nr = [r for r in D if r["case_id"] == cid and r["arm"] == "naive"]
        gr = [r for r in D if r["case_id"] == cid and r["arm"] == "governed"]
        out.append(f"| {cid} | {sum(r['score']['final']['correct'] for r in nr)}/{len(nr)} | {sum(r['score']['raw']['correct'] for r in gr)}/{len(gr)} | "
                   f"{sum(r['score']['final']['correct'] for r in gr)}/{len(gr)} | {sum(bool(r['score']['final']['leaks']) for r in nr)} | "
                   f"{sum(r['score']['final']['forbidden_action'] for r in nr)} | {sum(bool(r['binding_notes']) for r in gr)} |")
    out += ["", "Every answer, first seed (status · action · approval):", "", "| case | naive | governed bound |", "|---|---|---|"]
    for cid in sorted({r["case_id"] for r in D}, key=lambda c: (c[2], len(c), c)):
        def desc(r):
            a = r["final_answer"]; ra = a["recommended_action"]
            return f"{'✓' if r['score']['final']['correct'] else '✗'} {a['status']} · {ra['action']}" + (" · approval" if ra.get("approval_required") else "")
        n = next(r for r in D if r["case_id"] == cid and r["arm"] == "naive" and r["seed"] == seeds[0])
        g = next(r for r in D if r["case_id"] == cid and r["arm"] == "governed" and r["seed"] == seeds[0])
        out.append(f"| {cid} | {desc(n)} | {desc(g)} |")
    S = rows("d_sensitivity.jsonl")
    if S:
        out += ["", "## D · Sensitivity model (one seed): correct", "", "| case | naive | governed raw | governed bound |", "|---|---|---|---|"]
        for cid in sorted({r["case_id"] for r in S}, key=lambda c: (c[2], len(c), c)):
            n = next(r for r in S if r["case_id"] == cid and r["arm"] == "naive")
            g = next(r for r in S if r["case_id"] == cid and r["arm"] == "governed")
            out.append(f"| {cid} | {tick(n['score']['final']['correct'])} | {tick(g['score']['raw']['correct'])} | {tick(g['score']['final']['correct'])} |")
    D2 = rows("d2.jsonl")
    if D2:
        out += ["", "## D2 · Verifier and judge on the held-out pairs", "", "| pair | category | gold | verifier | judge |", "|---|---|---|---|---|"]
        for r in D2:
            out.append(f"| {r['pair_id']} | {r['category']} | {'supported' if r['gold'] else 'unsupported'} | {tick(r['verifier'] == r['gold'])} | "
                       f"{tick(r.get('judge') == r['gold']) if r.get('judge') is not None else '—'} |")
    E = rows("e_evidence.jsonl")
    if E:
        out += ["", "## E · Ablations, evidence level: labelled-invalid units in context per case", ""]
        variants = sorted({r["arm"] for r in E})
        out += ["| case | " + " | ".join(variants) + " |", "|---|" + "---|" * len(variants)]
        for cid in sorted({r["case_id"] for r in E}, key=lambda c: (c[2], len(c), c)):
            out.append(f"| {cid} | " + " | ".join(str(next(r for r in E if r["case_id"] == cid and r["arm"] == v)["score"]["context"]["invalid"]) for v in variants) + " |")
    (ROOT / "docs" / "source" / "report.src.md").write_text("\n".join(out) + "\n")
    print("docs/source/report.src.md written")


if __name__ == "__main__":
    main()
