"""README.md from README.template.md and the published run (Proof Contract §1: the README is rendered from facts).

    uv run python tools/build_readme.py [--check]

{{fact}} placeholders take the published run's facts (evidence/runs/<run>/results.json → facts); an unknown fact is an
error. Markers expand to tables built from the package: <!-- proof:reality --> (the execution profile, each REAL item
with its check), <!-- proof:experiments -->, <!-- proof:claim-example --> (one claim traced to its raw files) and
<!-- proof:history --> (the published run and the runs before it). --check only compares; stale() is what
tools/verify_evidence.py calls.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "vendor"))
from evidence_kit.facts import Facts  # noqa: E402

TEMPLATE, OUT = ROOT / "README.template.md", ROOT / "README.md"
HEADER = "<!-- Generated by tools/build_readme.py from README.template.md and the published run. Edit the template, not this file. -->\n"
EXAMPLE = ("P1-C03", "P1-R3", "P1-R3-C01")


def published() -> tuple[dict, dict, list[dict]]:
    pub = json.loads((ROOT / "evidence" / "published.json").read_text())
    run = ROOT / "evidence" / "runs" / pub["run_id"]
    res = json.loads((run / "results.json").read_text())
    checks = [json.loads(x) for x in (run / "checks.jsonl").read_text().splitlines() if x.strip()]
    return pub, res, checks


def cell(s: str) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def render() -> str:
    pub, res, checks = published()
    F = Facts()
    for k, f in res["facts"].items():
        F.d[k] = f
    # {{fact|p1}}: a list of harness experiment ids (R1, R2) shown with the contract's article prefix (P1-R1, P1-R2)
    tpl = re.sub(r"\{\{([\w.]+)\|p1\}\}", lambda m: re.sub(r"\bR(\d+)\b", r"P1-R\1", str(res["facts"][m.group(1)]["value"])), TEMPLATE.read_text())
    text = F.resolve(tpl, "README.template.md")
    rid = pub["run_id"]
    rows = ["| Class | What | Shown by |", "|---|---|---|"]
    for c in res["profile"]["classes"]:
        for i in c["items"]:
            rows.append(f"| {c['class']} | {cell(i['text'])} | {('`' + i['check'] + '`') if i.get('check') else '—'} |")
    text = text.replace("<!-- proof:reality -->", "\n".join(rows))
    rows = ["| Id | Experiment | Question | Checks | Result |", "|---|---|---|---|---|"]
    for x in res["experiments"]:
        k = x["counts"]
        n = f"{k['PASS']} pass" + (f", {k['EXPECTED_FAILURE']} expected failure" if k["EXPECTED_FAILURE"] else "") + (f", {k['FAIL']} fail" if k["FAIL"] else "")
        rows.append(f"| `{x['id']}` | {cell(x['title'])} | {cell(x['question'])} | {n} | {x['result']} |")
    text = text.replace("<!-- proof:experiments -->", "\n".join(rows) + "\n\nEach experiment states its claim, hypothesis, setup, "
                        "variable, invariant and limitations in `proof/experiments.toml`; every check is a comparison of facts read "
                        "from the run, evaluated by `evidence_kit.proof`. A control check states a safeguard's invariant with the "
                        "safeguard absent and expects it to break: EXPECTED_FAILURE is that control working.")
    cl = next(c for c in res["claims"] if c["id"] == EXAMPLE[0])
    ck = next(c for c in checks if c["id"] == EXAMPLE[2])
    files = sorted({e["path"] for e in ck["evidence"]}) + [f"evidence/runs/{rid}/raw/experiments/R3/{f}" for f in ("approvals.jsonl", "policy.jsonl", "audit.jsonl")]
    ex = ["```", f"article claim   {cl['statement']}", f"   ↓", f"claim           {cl['id']} ({cl['verdict']}; checks {len(cl['checks'])})",
          f"   ↓", f"experiment      {EXAMPLE[1]} · {next(x['title'] for x in res['experiments'] if x['id'] == EXAMPLE[1])}",
          f"   ↓", f"check           {ck['id']}: {ck['description']}", f"                fact {ck['fact']} {ck['expected']} → actual {ck['actual']} → {ck['status']}",
          f"   ↓", "raw evidence    " + "\n                ".join(files), "```"]
    text = text.replace("<!-- proof:claim-example -->", "\n".join(ex))
    hist = [f"**Published run:** `{rid}`, promoted {pub['promoted_at']}: {pub['reason']}"]
    if pub.get("note"):
        hist.append(f"*{pub['note']}*")
    hist += ["", "| Earlier run | Why it was replaced |", "|---|---|"]
    hist += [f"| `{h['run_id']}` | {cell(h['reason'])} |" for h in pub["history"]]
    hist += ["", "What changed between the original publication and this run, metric by metric: "
             "`../docs/proof-standardization/proof-refresh-delta.md` (in the article repository)."]
    text = text.replace("<!-- proof:history -->", "\n".join(hist))
    return HEADER + text


def stale() -> list[str]:
    want = render()
    have = OUT.read_text() if OUT.exists() else ""
    return [] if want == have else ["README.md differs from README.template.md rendered with the published run's facts (uv run python tools/build_readme.py)"]


def main() -> int:
    if "--check" in sys.argv:
        s = stale()
        print("\n".join(s) or "README.md is current")
        return 1 if s else 0
    OUT.write_text(render())
    print(f"README.md rendered from the published run ({len(OUT.read_text().splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
