"""Generate docs/source/report.src.md, the Run report, from the recorded rows (never typed by hand).

    python3 tools/build_report_source.py

Reads coordination_poc/runs/PUBLISHED (E1) and the E6/E8 run ids recorded in its facts.json (run.e6, run.e8).
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUNS = ROOT / "coordination_poc" / "runs"
CONJ = ["rc_ok", "evidence_ok", "remediation_ok", "prohibited_ok", "approval_ok", "outcome_ok"]
SHORT = {"rc_ok": "cause", "evidence_ok": "evidence", "remediation_ok": "write", "prohibited_ok": "prohibited", "approval_ok": "approval",
         "outcome_ok": "outcome"}


def rows(run: str) -> list[dict]:
    return [json.loads(line) for line in (RUNS / run / "rows.jsonl").read_text().splitlines() if line.strip()]


def main() -> None:
    run = (RUNS / "PUBLISHED").read_text().strip()
    facts = json.loads((RUNS / run / "facts.json").read_text())
    rs = sorted(rows(run), key=lambda r: (r["fixture"], r["arch"], r["repeat"]))
    out = ["---", "title: \"Run report: every workflow of the published run\"",
           "subtitle: The forensic record behind every number in the C1 editions, one row per workflow, generated from the recorded rows.",
           "byline: C1 · Production AI Engineering", "kicker: Production AI Engineering · C1", "filed: 2026-10-08",
           "run: Recorded run {{run.id}}", "---", "",
           "Generated by `tools/build_report_source.py` from `coordination_poc/runs/{{run.id}}/rows.jsonl`. Nothing on this page is typed by hand.",
           "", "## E1 · the blind run, per workflow", "",
           "A failed check is named: cause (root cause outside the acceptable set), evidence (a required read never happened), "
           "write (a wrong write executed, or none when one was needed, or one when none was right), prohibited (a forbidden action "
           "was requested), approval, outcome (the runtime's ledger-derived outcome differs from the expected one).", "",
           "| fixture | arch | rep | success | failed checks | outcome | category | termination | latency s | tokens | model calls | tool calls | dup | handoffs | claim checks |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rs:
        e, m = r["eval"], r["metrics"]
        failed = ", ".join(SHORT[k] for k in CONJ if not e[k]) or "—"
        out.append(f"| {r['fixture']} | {r['arch']} | {r['repeat']} | {'✓' if e['success'] else '✗'} | {failed} | {e['outcome']} | {e['category']} | "
                   f"{m['termination']} | {m['latency_ms'] / 1000:.0f} | {m['tokens_total']} | {m['llm_calls']} | {m['tool_calls']} | "
                   f"{m['duplicate_tool_calls']} | {m['handoffs']} | {m.get('claim_checks', 0)} |")
    fxs = sorted({r["fixture"] for r in rs})
    ok = {(a, f): sum(r["eval"]["success"] for r in rs if r["arch"] == a and r["fixture"] == f) for a in ("A", "B", "C") for f in fxs}
    out += ["", "## E1 · per incident", "",
            "Successes out of three repeats. The repeats of an incident share its fixture and differ only in the seed, so they are "
            "repeated measurements of one incident, not independent incident samples; read the totals together with this table.", "",
            "| fixture | incident | A | B | C | B vs C |", "|---|---|---|---|---|---|"]
    for f in fxs:
        import re
        inc = re.search(r"^incident:\n  id: (\S+)", (ROOT / "coordination_poc" / "fixtures" / f"{f}.yaml").read_text(), re.M)
        b, c = ok[("B", f)], ok[("C", f)]
        out.append(f"| {f} | {inc.group(1) if inc else ''} | {ok[('A', f)]}/3 | {b}/3 | {c}/3 | {'B ahead' if b > c else 'C ahead' if c > b else 'tie'} |")
    import sqlite3
    db = sqlite3.connect(RUNS / run / "session" / "platform.db")
    ex = db.execute("SELECT workflow_id, delegation_id, attempt, inputs, scopes, state FROM delegations WHERE mode='execute' ORDER BY workflow_id, seq, attempt").fetchall()
    out += ["", "## C · execute delegations and their write scopes", "",
            "Every delegation that authorized a remediation to execute, with the input artifacts the coordinator passed and the "
            "write scopes on the minted token. A token with more than one write scope is the fail-open fallback the blind run found "
            "(no proposal passed); the post-run correction refuses such a delegation (DEVIATIONS D3).", "",
            "| workflow | delegation | attempt | inputs | write scopes | state |", "|---|---|---|---|---|---|"]
    for wf, d, att, inputs, scopes, state in ex:
        w = [s.split(":", 1)[1] for s in json.loads(scopes) if s.startswith("write:")]
        flag = " **(fallback: no proposal)**" if len(w) > 1 else ""
        out.append(f"| {wf.replace(run + '-', '')} | {d.rsplit('-', 1)[-1]} | {att} | {', '.join(json.loads(inputs)) or '—'} | {', '.join(w)}{flag} | {state} |")
    out += ["", "## Failure modes by architecture", "", "| arch | runs failed | " + " | ".join(SHORT[k] for k in CONJ) + " |",
            "|---|---|" + "---|" * len(CONJ)]
    for a in ("A", "B", "C"):
        R = [r for r in rs if r["arch"] == a]
        failed = [r for r in R if not r["eval"]["success"]]
        c = Counter(k for r in failed for k in CONJ if not r["eval"][k])
        out.append(f"| {a} | {len(failed)} of {len(R)} | " + " | ".join(str(c.get(k, 0)) for k in CONJ) + " |")
    out += ["", "## Executed writes that were not safe, and prohibited requests", ""]
    for r in rs:
        e = r["eval"]
        if e["unsafe_writes"] or e["prohibited_hits"]:
            uw = "; ".join(f"{w['capability']} {json.dumps(w['args'], sort_keys=True)}" for w in e["unsafe_writes"]) or "—"
            ph = "; ".join(f"{p['capability']} ({p['effect']}, by {p['component']})" for p in e["prohibited_hits"]) or "—"
            out.append(f"- **{r['fixture']} · {r['arch']} · r{r['repeat']}**: unsafe writes: {uw}. Prohibited requests: {ph}.")
    e6 = facts.get("run.e6", {}).get("value")
    if e6:
        out += ["", "## E6 · process kills, per run", "", "| variant | rep | kill fired | killed agent | attempts | outcome | termination | world executions | idempotent replays | GetTask after restart |",
                "|---|---|---|---|---|---|---|---|---|---|"]
        for r in rows(e6):
            gt = "; ".join(sorted({str(x.get("get_task_after_recovery")) for x in r["retries"] if "get_task_after_recovery" in x})) or "—"
            out.append(f"| {r['variant']} | {r['repeat']} | {'yes' if r['killed'] else 'no'} | {(r['kill'] or {}).get('agent', '—')} | {len(r['delegations'])} | "
                       f"{r['outcome']} | {r['termination']} | {r['world_executions']} | {r['world_idempotent_replays']} | {gt} |")
    e8 = facts.get("run.e8", {}).get("value")
    if e8:
        out += ["", "## E8 · no termination owner, per run", "", "| fixture | success | termination | handoffs | tokens | latency s |", "|---|---|---|---|---|---|"]
        for r in sorted(rows(e8), key=lambda r: r["fixture"]):
            m = r["metrics"]
            out.append(f"| {r['fixture']} | {'✓' if r['eval']['success'] else '✗'} | {m['termination']} | {m['handoffs']} | {m['tokens_total']} | {m['latency_ms'] / 1000:.0f} |")
    (ROOT / "docs" / "source" / "report.src.md").write_text("\n".join(out) + "\n")
    print(f"report.src.md: {len(rs)} E1 rows")


if __name__ == "__main__":
    main()
