#!/usr/bin/env python3
"""Render layered_architecture_poc/README.md from its template, with every measured number resolved from facts.json.

    python3 tools/build_poc_readme.py            # render
    python3 tools/build_poc_readme.py --check    # fail if the rendered README is missing or stale

The POC folder is what gets published, so its README is read on its own: links must be relative to the folder, and no
number in it may be typed by hand. The template holds {{fact}} tokens, resolved by the same resolver the publications
use, and each use is recorded in docs/evidence-uses.json.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_docs as bd  # noqa: E402

POC = bd.ROOT / "layered_architecture_poc"
TEMPLATE = POC / "README.template.md"
OUT = POC / "README.md"
HEADER = "<!-- Generated by tools/build_poc_readme.py from README.template.md. Edit the template, not this file. -->\n\n"


def render() -> tuple[str, dict]:
    uses: dict = {}
    body = bd.render_facts(TEMPLATE.read_text(), bd.load_facts(), "poc_readme", uses)
    return HEADER + body, uses


def main() -> int:
    text, uses = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print("FAIL layered_architecture_poc/README.md is stale: run python3 tools/build_poc_readme.py")
            return 1
        print(f"README.md is current · {len(uses)} fact(s) resolved")
        return 0
    OUT.write_text(text)
    print(f"layered_architecture_poc/README.md: {len(text.split())} words, {len(uses)} fact(s) resolved from facts.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
