#!/usr/bin/env python3
"""Copy the reader-facing documents into the POC, so the published folder stands on its own.

    python3 tools/sync_poc_docs.py            # sync, then report what changed
    python3 tools/sync_poc_docs.py --check    # fail if a copy is missing or stale

The bundle keeps its documents at the bundle root, next to the figures and the publication tracks. The POC is what
gets published to the repository, and a reader who finds it there should not have to guess where the evidence
discussion lives. So the Markdown documents are copied into `layered_architecture_poc/docs/published/`, each with a header
saying it is generated and where it came from.

Only Markdown is copied. The HTML and PDF editions, the Lab Console and the figures stay in the release bundle: they
are large, they are built artefacts, and the repository copy is for reading and reviewing.
"""

from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
POC = HERE / "layered_architecture_poc"
OUT = POC / "docs" / "published"

# Bundle document → name inside the POC. Only documents a reader of the repository needs.
DOCS = {
    "docs/claim_evidence_matrix.md": "claim-evidence-matrix.md",
    "docs/real_vs_simulated.md": "real-vs-simulated.md",
    "docs/monolith_fairness_review.md": "monolith-fairness-review.md",
    "docs/layering_review.md": "layering-review.md",
    "docs/change-surface.md": "change-surface.md",
    "docs/benefit-evidence-map.md": "benefit-evidence-map.md",
    "docs/experiment-inventory.md": "experiment-inventory.md",
    "docs/design-review-checklist.md": "design-review-checklist.md",
    "docs/results/layered-agent-platform-evidence-check.md": "evidence-check.md",
    "docs/results/layered-agent-platform-run-report.md": "run-report.md",
    "docs/standardization/f2-standardization-report.md": "standardization-report.md",
    "docs/standardization/immutability-audit.md": "immutability-audit.md",
    "docs/standardization/f2-current-state-audit.md": "current-state-audit.md",
    "verification/test_accounting.md": "test-accounting.md",
    # verification/final_verification.md is deliberately not synced: the publication gate rewrites it every time it
    # runs, so a copy of it inside the POC would be stale by construction. It ships in the release bundle instead.
}
HEADER = ("<!-- Generated by tools/sync_poc_docs.py from {source} in the engineering bundle. Edit that file, not "
          "this copy. -->\n\n")


def body(source: Path) -> str:
    return HEADER.format(source=source.as_posix()) + source.read_text()


def main() -> int:
    check = "--check" in sys.argv
    OUT.mkdir(parents=True, exist_ok=True)
    stale, missing, written = [], [], []
    for rel, name in DOCS.items():
        src = HERE / rel
        if not src.exists():
            missing.append(rel)
            continue
        want = body(Path(rel))
        dst = OUT / name
        if not dst.exists() or dst.read_text() != want:
            if check:
                stale.append(name)
            else:
                dst.write_text(want)
                written.append(name)
    extra = sorted(p.name for p in OUT.glob("*.md") if p.name not in DOCS.values())
    for name in extra:
        if check:
            stale.append(f"{name} (no longer a source document)")
        else:
            (OUT / name).unlink()
    for m in missing:
        print("FAIL missing source document:", m)
    for s in stale:
        print("FAIL stale copy:", s)
    if not check:
        print(f"{len(DOCS)} document(s) in {OUT.relative_to(HERE)}; {len(written)} rewritten, {len(extra)} removed")
    elif not stale and not missing:
        print(f"{len(DOCS)} document(s) in {OUT.relative_to(HERE)} are current")
    return 1 if (stale or missing) else 0


if __name__ == "__main__":
    raise SystemExit(main())
